language: node_js

node_js:
- 6.2.0

sudo: false

branches:
  only:
    - master

script: npm run build



deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: $AWS_BUCKET
  acl: public_read
  local_dir: build

