languages:
  JavaScript: true
exclude_paths:
- "lib/**"
- "test/**"
- "example/**"
- "bin/**"
- "webpack.config.base.js"
- "webpack.config.development.js"
- "webpack.config.production.js"
- "LICENSE"
- "README.md"
- "config.json"
- "package.json"
- "generators/**/templates"
